on: push
name: Build and Generate Android Apk
env:
  SOLUTION_NAME: GitHubActionsDemoApp\GitHubActionDemo
  ANDROID_PROJECT_NAME: GitHubActionsDemoApp\GitHubActionDemo\GitHubActionDemo.Android
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building APK
        uses: ./action
        with:
          args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk GitHubActionsDemoApp\GitHubActionDemo\GitHubActionDemo.Android.csproj
      - name: Artifacts
        run: |
          mkdir -p apks
          cp GitHubActionsDemoApp\GitHubActionDemo\GitHubActionDemo.Android/bin/Debug/*.apk apks
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: apks
